version: "3"

services:
  botpress:
    image: botpress/server:v12_30_7
    ports:
      - "3001:3000"

  bridge:
    image: douglara/chatwoot-botpress-bridge:1
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=Testing1234
      - BOTPRESS_ENDPOINT=http://botpress:3000
      - BOTPRESS_BOT_ID=hello
      - CHATWOOT_ENDPOINT=https://chat.opencloudx.io/
      - CHATWOOT_BOT_TOKEN=password
    ports:
      - "3002:3000"
